# This is a basic workflow to help you get started with Actions

name: Update scores

# Controls when the workflow will run
on:
  #schedule:
  #  - cron: 30 18 * * *
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
      - www/data/domains.json

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install cpanm and multiple modules
        uses: perl-actions/install-with-cpanm@v1
        with:
          install: JSON::XS

      # Runs script
      - name: Update scores
        working-directory: code/
        run: |
          perl buildScores.pl

      - name: Commit changes to files
        working-directory: www/data/areas/
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update scores" || exit 0

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
